BEGIN;

DROP TABLE IF EXISTS outbox CASCADE;
DROP TABLE IF EXISTS attribute_index CASCADE;
DROP TABLE IF EXISTS decision_trace CASCADE;
DROP TABLE IF EXISTS shadowed_match CASCADE;
DROP TABLE IF EXISTS assignment CASCADE;
DROP TABLE IF EXISTS rule_version CASCADE;
DROP TABLE IF EXISTS assignment_rule CASCADE;
DROP TABLE IF EXISTS policy_version CASCADE;
DROP TABLE IF EXISTS policy CASCADE;
DROP TABLE IF EXISTS fact_event CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS attribute_definition CASCADE;
DROP TABLE IF EXISTS policy_category CASCADE;

COMMIT;
